name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-spp:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
           sudo docker stop gospp
           sudo docker rm gospp
           sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/go-spp:latest
           sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go-spp:latest
           sudo docker run -d -p 8080:8080 -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e DB_Username=${{ secrets.DB_Username }} -e DB_Password=${{ secrets.DB_Password }} -e DB_Host=${{ secrets.DB_Host }} -e DB_Port=${{ secrets.DB_Port }} -e DB_Name=${{ secrets.DB_Name }} -e SECRET_JWT=${{ secrets.SECRET_JWT }} -e CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} -e AI_KEY=${{ secrets.AI_KEY }} --name gospp ${{ secrets.DOCKERHUB_USERNAME }}/go-spp:latest